- src/common/EmojiTag.jsx
- 이모지태그 컴포넌트입니다.
- tailwind css 반응형 "md:text-sm lg:text-lg" 적용하였습니다.
-
-
> feat: 공통컴포넌트-이모지태그

- src/hooks/useDebounce.js
- `useDebounce` 훅 추가
- 스터디 검색에서 활용
- 브랜치 경로 맞습니다.
-
- `src/hooks` 폴더 생성
-
> feat: useDebounce 훅 추가

- src/common/modal/HabitListModal.jsx
> fix:습관 모달 취소 버튼 수정

- src/components/PasswordValidation.jsx
- src/components/StudyFormValidation.jsx
- src/pages/StudyCreatePage.jsx
- 테스트해보니 문제가 발생해서 수정하였습니다. 
-  onChange?.(newValue);  -> onChange?.(e); 로 수정
- 닉네임 2자 이상 설정 가능하도록 수정
-
-
> Feat/ 스터디 생성 페이지 에러 해결

- index.html
- src/components/PasswordValidation.jsx
- src/components/StudyFormValidation.jsx
- src/pages/StudyCreatePage.jsx
- 스터디 생성 시 배경 이미지만 선택해도 스터디 생성이 되는 문제 해결
- 폼 제출 시 빈값이 있는 경우 alert 추가
> Fix: (스터디생성) 모든 필드가 유효할 때만 버튼 활성화

- package-lock.json
- package.json
- src/components/StudyCard.jsx
- src/pages/home/BrowseStudyContainer.jsx
- src/pages/home/RecentViewedStudyContainer.jsx
- tailwind.config.js
- 
- 홈에서 스터디 시작날부터 1일로 표시
- 스터디 카드 눌렀을 때 url `/study/~` 로 변경 (기존: `/studies/~`)
- `npm install` : dayjs
-
> fix: 스터디 시작날을 1일로 표시. url 변경(studies > study)

- package.json
- src/hooks/useWheelScrollBar.js
- src/pages/home/RecentViewedStudySection.jsx
- 홈 - 최근 조회한 스터디 스크롤바 생성
-
-
-
> design: 홈-최근 조회한 스터디 스크롤바 생성

- src/AppRouter.jsx
- src/common/layout/Footer.jsx
- src/pages/home/index.jsx
- Footer 추가
- Footer 컴포넌트를 AppRouter.jsx에 추가하였습니다.
- 한샘님과 동혁님 페이지에서 브라우저 비율을 확대해보시면 푸터가 메인 섹션으로 올라와서 겹치는 문제가 있습니다.
-
> ui: footer

- src/api/habitApi.js
- src/pages/HabitPage.jsx
- fix: 습관 삭제 기능 추가
- 습관 수정 시 페이지에 수정 된 습관이 렌더됨
- 습관 체크 시 아직 완료 요청 안됨
> fix: 습관 삭제 기능 추가

- src/api/habitApi.js
- src/pages/HabitPage.jsx
- API axios 변경, 습관 삭제시 리스트 업데이트
- 수정 완료 누르면 수정 한 데이터 상태가 렌더 되고 새로 고침 해야 서버에 있는 데이터 렌더
- 습관 완료 처리 해도 아직 api 요청 안됨
> Feat/UI 오늘의습관

- src/api/habitApi.js
- src/api/studyApi.js
- src/pages/StudyModifyPage.jsx
- patch API, 습관기록표  habit API 문제 해결
-
-
-
> fix: 스터디 수정페이지 API 문제 해결

- src/components/PasswordValidation.jsx
- src/components/StudyFormValidation.jsx
- src/hooks/useDebounceCallback.js
- src/pages/StudyCreatePage.jsx
- src/pages/StudyDetailPage.jsx
- src/pages/StudyModifyPage.jsx
- 스터디 생성 광클 방지 문제
-  isSubmitting 상태 삭제하고 useDebounce 적용
-
-
> fix: 스터디 생성 페이지 useDebounce 적용

- src/components/HabitTracker.jsx
- src/pages/FocusPage.jsx
- src/pages/StudyCreatePage.jsx
- src/pages/StudyDetailPage.jsx
> fix: 스터디 상세페이지 습관기록

- src/components/HabitTracker.jsx
> Feat 습관 기록표 오늘 요일 하이라이트 추가

- src/components/FocusHeader.jsx
> refactor: 버튼 패딩조절

- src/pages/StudyModifyPage.jsx
> fix: 수정페이지 

- src/pages/StudyDetailPage.jsx
> fix: break-all 로 수정

- src/common/modal/HabitListModal.jsx
- src/pages/HabitPage.jsx
> fix: 습관 추가 글자 최대 20자 제한

- src/components/HabitTracker.jsx
- 현재 요일 표시 발자국 이미지 사이즈랑 통일 시켰슴다 
-
- 원작자 컨펌 받음
-
> refactor: 요일

- package-lock.json
- package.json
- src/api/uploadImage.js
- src/common/MessageBox2.jsx
- src/components/Skeleton.CreatePage.jsx
- src/pages/StudyCreatePage.jsx
- 스터디 생성페이지 추가 기능 수정
- 이미지 3개까지 추가 가능
- 추가한 이미지 삭제 가능
- 이미지 선택 시 type에 따라 paw(black, white) 다르게 적용
- alert -> ErrorMessage 메시지박스 적용 
- 이미지 로딩중 스피너 추가
- 수정 페이지에 적용
- 메시지박스 위치 조정
> Feat/스터디 생성페이지 수정

- src/pages/StudyDetailPage.jsx
> feat: 페이지 들어왔을 때 스크롤 초기화

- src/components/EmojiForm.jsx
> fix: 이모지 피커 클릭 시 스켈레톤 적용
